name: adminsuper
description: A new Flutter project

publish_to: 'none' # Remove this line if you're publishing the package

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper_plus: ^2.0.4  # This is compatible with Dart SDK >=2.12.0
  cupertino_icons: ^1.0.8  # Updated to the null-safe version
  supabase_flutter: ^2.8.0
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:  # Use `assets` instead of `AssetImage`
    - assets/image/
    - assets/image/backroundplsp.jpg.jpg
